ClusterName=lancluster
SlurmctldHost=node71

MpiDefault=none
ProctrackType=proctrack/cgroup
ReturnToService=2
SlurmctldPidFile=/run/slurmctld.pid
SlurmdPidFile=/run/slurmd.pid
SlurmdSpoolDir=/var/spool/slurmd
SlurmUser=slurm
StateSaveLocation=/var/spool/slurmctld
SwitchType=switch/none
TaskPlugin=task/affinity,task/cgroup

SchedulerType=sched/backfill
SelectType=select/cons_tres
SelectTypeParameters=CR_Core

SlurmctldPort=6817
SlurmdPort=6818

AuthType=auth/munge
CryptoType=crypto/munge

# 按实际 CPU 核数改
NodeName=node71  NodeAddr=192.168.30.71  CPUs=8 State=UNKNOWN
NodeName=node101 NodeAddr=192.168.31.101 CPUs=8 State=UNKNOWN

PartitionName=debug Nodes=node71,node101 Default=YES MaxTime=INFINITE State=UP